### ISSUE TITLE
Big infrastructure features todo list

### ISSUE THREAD

**Issue by lahmatiy** [discoveryjs/jora#36]
- [x] AST
- [ ] Immutable paths hoisting (reduce computations -> performance)
- [ ] Smart computation caching across queries
- [ ] Query parts performance stat
- [ ] Query transforming, e.g. query merge, subquery to a query, context inlining
- [ ] Syntax highlighting
- [ ] Prettifier
- [x] Move jison to dev dependencies
- [ ] Debugging (step by step evaluation)
- [ ] Input data shape prediction suitable for a query (based on touching paths)
